### ISSUE TITLE
make diagrams that show the current situation, the situation that government wants, etc.

### ISSUE THREAD

**Issue by judithnaomi** [Cvalladares/gula_apong_mobile#11]

**Comment by judithnaomi** [comment]
I put them in the report, can anyone check and add? I did not know what to put next to the arrows from Ministry to App and from Admin to App..

**Comment by Huiggy** [comment]
Ministry to App: Incentives

App to Admin: Salary(?, confirm with prof ibrahim, should reward admin too)

Added: App to Producer: Incentives
