### ISSUE TITLE
Translation for the app (English -> Malay)

### ISSUE THREAD

**Issue by Huiggy** [Cvalladares/gula_apong_mobile#18]

**Comment by judithnaomi** [comment]
keywords to be translated are:

Hi Kuan, could you put the Malay translation behind the words? If anyone thinks of any other words, please add!

Hello
Welcome
Log in
Password
Username
Language
Select
Insert
Amount of Gula Apong (in kg) produced this week
Number of productive trees
Number of trees
Date
Edit
Remove
Close
Bye!
Thanks
Submit
Price
Selling price

**Comment by Huiggy** [comment]
closed.
