### ISSUE TITLE
Interview questions/flows to potential users

### ISSUE THREAD

**Issue by Huiggy** [Cvalladares/gula_apong_mobile#19]

**Comment by judithnaomi** [comment]
could you work on this Kuan?

**Comment by judithnaomi** [comment]
I will also work on it!

**Comment by Huiggy** [comment]
Interview Questions (PRODUCERS)
---------------------------------------
(close questions)
A. App
1. This app can help assisting in my farm.
2. This app interface is user friendly.
3. This app has attractive design.
4. This app is easy to use.
5. This app is useful in my daily task.

B. Function
1. I can easily understand the functions of the app.
2. I can use without assistance.
3. I will continue to use this app in my daily task.
4. I will recommend this app to my friends.

(open questions)
1. What benefits do you get from this app? How the app assist in your farm?
2. Suggestion/comment for future development.

**Comment by Huiggy** [comment]
Interview Questions (MINISTRY)
----------------------------------
(close questions)
A. App

1. This app can help overseeing the current status of gula apong producers.
2. This app interface is user friendly.
3. This app has attractive design.
4. This app is easy to use.
5. This app is useful in my daily task.
6. This app has achieve minimum requirements for the objectives.
7. This app has a market potential for gula apong sales.

B. Function

1. I can easily understand the functions of the app.
2. I can use without assistance.
3. I will continue to use this app in my daily task.
4. I will recommend this app to farmers.
(open questions)

What benefits do you get from this app? How the app assist in your working area?
Suggestion/comment for future development.

**Comment by judithnaomi** [comment]
Nice! Could you put it in the corresponding section in the report? Merge them with mine?

**Comment by Huiggy** [comment]
Interview Questions (PRODUCERS) - MALAY
(close questions)
A. Aplikasi

1. Aplikasi ini dapat membantu saya dalam kerja kebun.
2. Aplikasi ini sangat mesra pengguna.
3. Aplikasi ini mempunyai reka bentuk yang menarik.
4. Aplikasi ini sangat senang untuk digunakan.
5. Aplikasi ini sangat membantu dalam kerja harian saya.

B. Fungsi

1. Saya dapat memahami fungsi aplikasi ini.
2. Saya dapat guna aplikasi ini tanpa bantuan.
3. Saya akan terus menggunakan aplikasi ini dalam kerja harian saya.
4. Saya akan mensyorkan aplikasi ini kepada rakan saya.

(open questions)

Apakah faedah/kebaikan yang anda akan dapat dari aplikasi ini? Bagaimanakan aplikasi ini membantu anda melaksanakan tugas di tempat kerja anda?
Cadangan/komen penambahbaikan aplikasi ini.

**Comment by Huiggy** [comment]
Interview Questions (MINISTRY)
--------------------------
(close questions)
A. App

1. Aplikasi ini dapat membantu saya untuk melihat situasi kini daripada pengeluar gula apong.
2. Aplikasi ini sangat mesra pengguna.
3. Aplikasi ini mempunyai reka bentuk yang menarik.
4. Aplikasi ini sangat senang untuk digunakan.
5. Aplikasi ini sangat membantu dalam kerja harian saya.
6. Aplikasi ini telah mempunyai minimum keperluan untuk mencapai objektif. 
7. Aplikasi ini mempunyai potensi pasaran bagi gula apong.

B. Function

1. Saya dapat memahami fungsi aplikasi ini.
2. Saya dapat guna aplikasi ini tanpa bantuan.
3. Saya akan terus menggunakan aplikasi ini dalam kerja harian saya.
4. Saya akan mensyorkan aplikasi ini kepada petani-petani gula apong.

(open questions)
What benefits do you get from this app? How the app assist in your working area?
Suggestion/comment for future development.
